import { Figtree } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Navbar } from "@/Components/Navbar";






const figTree = Figtree({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${figTree.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar></Navbar>
        {children}
        <Toaster></Toaster>
        </body>
    </html>
  );
}
